-- This is the definitive script to set up the database schema from scratch.
-- It uses the modern IDENTITY column syntax preferred by Supabase.

-- Drop tables in reverse order of creation to avoid dependency issues.
DROP TABLE IF EXISTS public.health_analysis_answers;
DROP TABLE IF EXISTS public.health_analysis;
DROP TABLE IF EXISTS public.health_intake;

-- 1. Health Intake Table
-- Stores the initial user information and a path to their uploaded report.
CREATE TABLE public.health_intake (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    session_id uuid NOT NULL,
    name text,
    age integer,
    gender text,
    height numeric,
    weight numeric,
    units text,
    language text,
    diet text,
    occupation text,
    sleep text,
    report_path text
);

-- 2. Health Analysis Table
-- Tracks the status of an analysis session and stores the final report.
CREATE TABLE public.health_analysis (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    session_id uuid NOT NULL,
    status text,
    extracted_text jsonb,
    generated_questions jsonb,
    error_message text,
    final_report text -- This will store the final Markdown report from AIRA
);

-- 3. Health Analysis Answers Table
-- Stores each individual answer from the user Q&A.
CREATE TABLE public.health_analysis_answers (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    session_id uuid NOT NULL,
    question text NOT NULL,
    answer text NOT NULL
);

-- 4. Setup Indexes and Security
-- Add an index on session_id for faster lookups.
CREATE INDEX IF NOT EXISTS health_analysis_answers_session_id_idx ON public.health_analysis_answers(session_id);

-- Enable Row Level Security on all tables.
ALTER TABLE public.health_intake ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_analysis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_analysis_answers ENABLE ROW LEVEL SECURITY;

-- Grant all permissions to Supabase's default roles.
GRANT ALL ON TABLE public.health_intake TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.health_analysis TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.health_analysis_answers TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- --- END OF SCRIPT --- 