export const ayuvBenefits = [
  "Track your daily steps and stay motivated to move more with AYUV.",
  "Monitor your heart rate trends for early detection of issues.",
  "Get personalized reminders for medication and supplements.",
  "Easily book doctor appointments and never miss a checkup.",
  "Access your health records anytime, anywhere, securely.",
  "Share your medical history with doctors in one click.",
  "Visualize your sleep patterns and improve your rest.",
  "Connect your wearable devices for a complete health overview.",
  "Receive AI-powered health tips tailored to your lifestyle.",
  "Join wellness challenges and compete with friends.",
  "Log your meals and track your nutrition effortlessly.",
  "Set and achieve your fitness goals with progress tracking.",
  "Get alerts for abnormal vital signs instantly.",
  "Manage your family's health profiles in one place.",
  "Access telemedicine consultations from home.",
  "Store and organize all your lab results digitally.",
  "Receive vaccination reminders for you and your family.",
  "Track your water intake and stay hydrated.",
  "Get mental health support and mindfulness resources.",
  "Monitor your blood pressure and spot trends early.",
  "Keep a digital diary of your symptoms for better care.",
  "Get notified about upcoming health events and webinars.",
  "Find trusted healthcare providers near you.",
  "Access emergency contacts and info instantly.",
  "Receive personalized preventive care suggestions.",
  "Track your child's growth and immunization milestones.",
  "Get reminders for annual health screenings.",
  "Easily upload and store prescriptions.",
  "Visualize your health journey with beautiful charts.",
  "Join a supportive community focused on wellness.",
  "Manage chronic conditions with smart tracking tools.",
  "Get daily wellness inspiration and motivation.",
  "Access curated health articles and resources.",
  "Share your progress with your care team securely.",
  "Receive alerts for medication refills.",
  "Track your recovery after surgery or illness.",
  "Get insights on your activity, sleep, and nutrition.",
  "Set reminders for doctor follow-ups.",
  "Access your insurance details and claims easily.",
  "Get support for healthy habits and routines.",
  "Track allergies and avoid triggers.",
  "Receive tips for stress management and relaxation.",
  "Monitor your glucose levels and trends.",
  "Get reminders for dental and eye checkups.",
  "Access your health data across all devices.",
  "Visualize your progress with easy-to-read dashboards.",
  "Get notified about new AYUV features and updates.",
  "Easily export your health data when needed.",
  "Track your BMI and body composition.",
  "Get personalized exercise recommendations.",
  "Access AYUV in multiple languages.",
  "Join wellness webinars and learn from experts.",
  "Get support for quitting smoking or other habits.",
  "Track your mood and mental well-being.",
  "Receive reminders for hydration and nutrition.",
  "Access trusted health news and updates.",
  "Get support for women's health and wellness.",
  "Track your menstrual cycle and fertility.",
  "Get reminders for flu shots and boosters.",
  "Access AYUV securely with multi-factor authentication.",
  "Visualize your medication adherence over time.",
  "Get support for healthy aging and senior care.",
  "Track your physical therapy progress.",
  "Access AYUV from web, mobile, and tablet.",
  "Get reminders for regular exercise.",
  "Track your cholesterol and lipid levels.",
  "Get support for healthy eating habits.",
  "Access AYUV's help team 24/7.",
  "Track your oxygen saturation (SpO2).",
  "Get reminders for skin checks and dermatology visits.",
  "Access your health summary for travel or emergencies.",
  "Track your vaccination status and history.",
  "Get support for managing allergies and asthma.",
  "Track your calorie intake and expenditure.",
  "Get reminders for prostate and breast health checks.",
  "Access AYUV's privacy-first health platform.",
  "Track your waist-to-hip ratio and health risks.",
  "Get support for managing diabetes.",
  "Track your medication side effects and report them.",
  "Get reminders for hearing and vision tests.",
  "Access AYUV's secure document storage.",
  "Track your family's health history.",
  "Get support for sleep improvement.",
  "Track your vaccination appointments.",
  "Get reminders for annual physicals.",
  "Access AYUV's AI-powered symptom checker.",
  "Track your hydration and electrolyte balance.",
  "Get support for managing hypertension.",
  "Track your physical activity and sedentary time.",
  "Get reminders for bone health and osteoporosis checks.",
  "Access AYUV's community forums.",
  "Track your health goals and celebrate achievements.",
  "Get support for managing pain and discomfort.",
  "Track your medication allergies and reactions.",
  "Get reminders for cancer screenings.",
  "Access AYUV's secure health sharing tools.",
  "Track your health insurance renewals.",
  "Get support for healthy pregnancy and parenting.",
  "Track your immunization coverage.",
  "Get reminders for specialist visits.",
  "Access AYUV's personalized health dashboard."
]; 