export const mockDashboardData = {
  user: {
    name: "Rahul Sharma",
    avatarUrl: "/placeholder.svg?height=100&width=100",
  },
  vitals: [
    {
      name: "Heart Rate",
      value: "72",
      unit: "bpm",
      timestamp: "Today, 10:45 AM",
      status: "Normal",
      trend: "stable",
      historyLink: "/vitals/heart-rate",
    },
    {
      name: "Blood Pressure",
      value: "118/78",
      unit: "mmHg",
      timestamp: "Today, 10:45 AM",
      status: "Normal",
      trend: "down",
      historyLink: "/vitals/blood-pressure",
    },
    {
      name: "Blood Glucose",
      value: "142",
      unit: "mg/dL",
      timestamp: "Yesterday, 7:30 PM",
      status: "Monitor",
      trend: "up",
      historyLink: "/vitals/blood-glucose",
    },
    {
      name: "SpO2",
      value: "98",
      unit: "%",
      timestamp: "Today, 10:45 AM",
      status: "Normal",
      trend: "stable",
      historyLink: "/vitals/spo2",
    },
  ],
  wearableData: {
    steps: {
      current: 7500,
      goal: 10000,
    },
    sleep: {
      duration: "7h 15m",
      hours: 7.25,
      goal: 8,
    },
    activeMinutes: {
      current: 35,
      goal: 60,
    },
    activityLink: "/activity",
  },
  appointments: [
    {
      id: "apt-1",
      doctorName: "Dr. Priya Mehta",
      specialty: "Cardiologist",
      purpose: "Follow-up Consultation",
      dateTime: "Tomorrow, 2:30 PM",
      location: "City Hospital",
      type: "in-person",
      detailsLink: "/appointments/apt-1",
    },
    {
      id: "apt-2",
      doctorName: "Dr. Vikram Singh",
      specialty: "General Physician",
      purpose: "Telemedicine Consultation",
      dateTime: "Friday, 11:00 AM",
      location: "Virtual Visit",
      type: "telemedicine",
      detailsLink: "/appointments/apt-2",
      joinLink: "/appointments/apt-2/join",
    },
  ],
  medications: [
    {
      id: "med-1",
      name: "Atorvastatin",
      dosage: "10mg, 1 tablet",
      nextDoseTime: "Today, 9:00 PM",
      instructions: "Take with food",
      status: "upcoming",
    },
    {
      id: "med-2",
      name: "Metformin",
      dosage: "500mg, 1 tablet",
      nextDoseTime: "Today, 2:00 PM",
      instructions: "Take after lunch",
      status: "due",
    },
    {
      id: "med-3",
      name: "Vitamin D3",
      dosage: "1000 IU, 1 capsule",
      nextDoseTime: "Today, 8:00 AM",
      status: "taken",
    },
  ],
  activities: [
    {
      id: "act-1",
      iconName: "FileText",
      description: "Lab results for Blood Test uploaded",
      timestamp: "Today, 11:30 AM",
      link: "/records/lab-1",
    },
    {
      id: "act-2",
      iconName: "UserCheck",
      description: "Consent granted to Dr. Sharma for 7 days",
      timestamp: "Yesterday, 3:15 PM",
      link: "/consents",
    },
    {
      id: "act-3",
      iconName: "CalendarClock",
      description: "Appointment with Dr. Mehta confirmed",
      timestamp: "Yesterday, 10:20 AM",
      link: "/appointments/apt-1",
    },
  ],
  insights: [
    {
      id: "ins-1",
      title: "Sleep Pattern Improvement",
      description:
        "Your average sleep duration has increased by 30 mins this week. Consistent sleep can boost your energy levels!",
      type: "observation",
      iconName: "TrendingUp",
      actionText: "View Sleep Data",
      actionLink: "/activity/sleep",
    },
    {
      id: "ins-2",
      title: "Activity Reminder",
      description:
        "We noticed your daily step count has been lower recently. Consider a short walk to help meet your activity goals.",
      type: "tip",
      iconName: "Lightbulb",
      actionText: "Set Activity Goal",
      actionLink: "/goals/activity",
    },
    {
      id: "ins-3",
      title: "Preventive Care",
      description:
        "Based on your profile, you are due for a dental check-up. Regular dental visits are important for your overall health.",
      type: "reminder",
      iconName: "ShieldAlert",
      actionText: "Find Dentists",
      actionLink: "/find-doctors?specialty=dentist",
    },
  ],
  quickActions: [
    {
      id: "qa-1",
      label: "Upload Record",
      icon: "FileUp",
      link: "/records/upload",
    },
    {
      id: "qa-2",
      label: "Share Summary",
      icon: "Share2",
      link: "/share",
    },
    {
      id: "qa-3",
      label: "Schedule Appointment",
      icon: "CalendarPlus",
      link: "/appointments/new",
    },
    {
      id: "qa-4",
      label: "Message Doctor",
      icon: "MessageSquare",
      link: "/messages",
    },
  ],
}
