export const mockMultiPatientData = {
  summary: {
    totalPatients: 24,
    criticalAlerts: 3,
    stablePatients: 18,
    monitoringPatients: 6,
  },
  alerts: [
    {
      id: "alert-001",
      patientId: "P001",
      patientName: "John Smith",
      type: "critical" as const,
      message: "Heart rate critically high: 145 BPM",
      timestamp: "2 minutes ago",
      acknowledged: false,
      unit: "ICU",
      room: "301",
    },
    {
      id: "alert-002",
      patientId: "P003",
      patientName: "Emily Johnson",
      type: "critical" as const,
      message: "Blood pressure dangerously low: 85/45 mmHg",
      timestamp: "5 minutes ago",
      acknowledged: false,
      unit: "Emergency",
      room: "ER-2",
    },
    {
      id: "alert-003",
      patientId: "P007",
      patientName: "Michael Brown",
      type: "warning" as const,
      message: "Temperature elevated: 101.8°F",
      timestamp: "8 minutes ago",
      acknowledged: false,
      unit: "General",
      room: "205",
    },
    {
      id: "alert-004",
      patientId: "P012",
      patientName: "Sarah Davis",
      type: "info" as const,
      message: "Medication administered successfully",
      timestamp: "12 minutes ago",
      acknowledged: true,
      unit: "Cardiology",
      room: "410",
    },
    {
      id: "alert-005",
      patientId: "P015",
      patientName: "Robert Wilson",
      type: "warning" as const,
      message: "Oxygen saturation below normal: 89%",
      timestamp: "15 minutes ago",
      acknowledged: false,
      unit: "ICU",
      room: "305",
    },
  ],
  patients: [
    {
      id: "P001",
      name: "John Smith",
      age: 67,
      gender: "Male",
      unit: "ICU",
      room: "301",
      status: "critical" as const,
      lastUpdate: "2 min ago",
      vitals: {
        heartRate: { value: 145, status: "Critical", trend: "up" as const },
        bloodPressure: { systolic: 160, diastolic: 95, status: "High" },
        temperature: { value: 99.2, status: "Normal", trend: "stable" as const },
        oxygenSaturation: { value: 92, status: "Monitor" },
      },
      alerts: 2,
      avatar: "/placeholder-user.jpg",
    },
    {
      id: "P002",
      name: "Maria Garcia",
      age: 45,
      gender: "Female",
      unit: "Cardiology",
      room: "408",
      status: "stable" as const,
      lastUpdate: "5 min ago",
      vitals: {
        heartRate: { value: 72, status: "Normal", trend: "stable" as const },
        bloodPressure: { systolic: 118, diastolic: 76, status: "Normal" },
        temperature: { value: 98.6, status: "Normal", trend: "stable" as const },
        oxygenSaturation: { value: 98, status: "Normal" },
      },
      alerts: 0,
      avatar: "/placeholder-user.jpg",
    },
    {
      id: "P003",
      name: "Emily Johnson",
      age: 34,
      gender: "Female",
      unit: "Emergency",
      room: "ER-2",
      status: "critical" as const,
      lastUpdate: "1 min ago",
      vitals: {
        heartRate: { value: 110, status: "High", trend: "up" as const },
        bloodPressure: { systolic: 85, diastolic: 45, status: "Critical" },
        temperature: { value: 97.8, status: "Low", trend: "down" as const },
        oxygenSaturation: { value: 94, status: "Monitor" },
      },
      alerts: 3,
      avatar: "/placeholder-user.jpg",
    },
    {
      id: "P004",
      name: "David Lee",
      age: 58,
      gender: "Male",
      unit: "General",
      room: "203",
      status: "monitoring" as const,
      lastUpdate: "3 min ago",
      vitals: {
        heartRate: { value: 88, status: "Normal", trend: "stable" as const },
        bloodPressure: { systolic: 135, diastolic: 85, status: "Monitor" },
        temperature: { value: 99.8, status: "Monitor", trend: "up" as const },
        oxygenSaturation: { value: 96, status: "Normal" },
      },
      alerts: 1,
      avatar: "/placeholder-user.jpg",
    },
    {
      id: "P005",
      name: "Lisa Anderson",
      age: 29,
      gender: "Female",
      unit: "General",
      room: "112",
      status: "stable" as const,
      lastUpdate: "7 min ago",
      vitals: {
        heartRate: { value: 68, status: "Normal", trend: "stable" as const },
        bloodPressure: { systolic: 110, diastolic: 70, status: "Normal" },
        temperature: { value: 98.4, status: "Normal", trend: "stable" as const },
        oxygenSaturation: { value: 99, status: "Normal" },
      },
      alerts: 0,
      avatar: "/placeholder-user.jpg",
    },
    {
      id: "P006",
      name: "James Wilson",
      age: 72,
      gender: "Male",
      unit: "ICU",
      room: "302",
      status: "monitoring" as const,
      lastUpdate: "4 min ago",
      vitals: {
        heartRate: { value: 95, status: "Monitor", trend: "up" as const },
        bloodPressure: { systolic: 145, diastolic: 90, status: "High" },
        temperature: { value: 100.1, status: "Monitor", trend: "up" as const },
        oxygenSaturation: { value: 93, status: "Monitor" },
      },
      alerts: 2,
      avatar: "/placeholder-user.jpg",
    },
  ],
}
